### ISSUE TITLE
compartment call issue

### ISSUE THREAD

**Issue by Drosophilid** [vaquerizaslab/fanc#23] opened 2020-07-06 12:30 UTC
Hi,
I'm working on Drosophila Hi-C data.
I have called the compartments by using command:
# fanc compartments -g genome.fa -e chrX.pdf chrX.hic chrX.ab -v chrX.ev.txt -s 0 -tmp
eigen vector values (chrX.ev.txt file) shows chromatin distribution as "A" and "B" compartment along chrX, but the plot looks strange (don't show negative values).
<img width="647" alt="Screenshot 2020-07-06 at 14 22 10" src="https://user-images.githubusercontent.com/64106867/86592623-1ebd2a00-bf94-11ea-9b64-ad1d54583214.png">

This is how compartments heatmap look like when I don't use "-s 0" option.
<img width="647" alt="Screenshot 2020-07-06 at 14 27 13" src="https://user-images.githubusercontent.com/64106867/86593120-f4b83780-bf94-11ea-9e83-5833c73df96d.png">

could you please explain how compartment calling works in FanC?

Thanks

**Comment by kaukrise** [comment] 2020-07-07 13:17
Hi, can you provide us with some additional information, so I can see what the issue might be?

- what is the resolution of the Hi-C matrix you are working with?
- what is your FAN-C version?
- can you paste the first couple of lines from the eigenvector file? Ideally showing the separate compartment calls you are describing

I am currently out of office, so please apologise any delay in my replies.

Best,
Kai

**Comment by Drosophilid** [comment] 2020-07-07 13:27
Hi Kai, thanks for the reply.

1. I have used 10kb bin size.
2. Fan-C version: 0.8.35
3. eigenvector file looks like:
X       1       10000   B       -0.004934328608214855   .
X       10001   20000   B       -0.004627970512956381   .
X       20001   30000   B       -0.0023755489382892847  .
X       30001   40000   B       -2.0910687453579158e-05 .
X       40001   50000   B       -0.0025988502893596888  .
X       50001   60000   B       -0.006515695247799158   .
X       60001   70000   B       -0.004939275328069925   .
X       70001   80000   B       -0.005263351369649172   .
X       80001   90000   A       0.0012980124447494745   .
X       90001   100000  A       -0.0    .
X       100001  110000  B       -0.008463512174785137   .
X       110001  120000  B       -0.006222791038453579   .

Thanks

**Comment by kaukrise** [comment] 2020-07-07 13:43
Thanks for the quick reply. This all looks good.

I don't have much firsthand experience with Drosophila Hi-C data, but this might not be a bug, but real biological signal. Sometimes the first eigenvector captures other genomic associations than the compartments. Let's see if we can get to the bottom of this. I would recommend the following:

- plot the X chromosome from the original Hi-C file using `fancplot` (use `-p square`)
- plot the AB file with fancplot the same way, but choose `-vmin -1 -vmax 1 -c bwr`
- plot the o/e values from the Hi-C with fancplot and `-e`

Also, could you count the number of A and B compartment calls in the eigenvector file? (`grep A | wc -l` and same with B)

Unfortunately I can't easily post full commands here, since I am on mobile, but you should be able to find all the relevant info from the docs!

**Comment by Drosophilid** [comment] 2020-07-08 12:53
plot the X chromosome from the original Hi-C file using fancplot (use -p square):
![Screen Shot 2020-07-08 at 12 39 04 PM](https://user-images.githubusercontent.com/64106867/86909232-0aa23580-c118-11ea-81c6-94a6038e992f.png)

plot the AB file with fancplot the same way, but choose -vmin -1 -vmax 1 -c bwr:
![Screen Shot 2020-07-08 at 2 49 51 PM](https://user-images.githubusercontent.com/64106867/86920604-4e9e3600-c12a-11ea-9f03-dcb3f72ed23e.png)

plot the o/e values from the Hi-C with fancplot and -e:
![Screen Shot 2020-07-08 at 2 50 21 PM](https://user-images.githubusercontent.com/64106867/86920663-61186f80-c12a-11ea-9d75-c328d76a4561.png)

total A-compartment= 5386
total B-compartment= 1430

**Comment by kaukrise** [comment] 2020-07-08 13:14
Thanks a lot. The AB plot definitely does not look normal (the other two do).

To check if this is indeed a bug, could you try the compartment analysis on the [FAN-C example data](https://vaquerizaslab.github.io/fanc/getting_started.html#id5)?

https://vaquerizaslab.github.io/fanc/fanc-executable/fanc-analyse-hic/ab_compartments.html

Is there any chance that the compartment analysis has been run with an older version of FAN-C?

**Comment by Drosophilid** [comment] 2020-07-08 13:58
Dear KauKrise,
I have used the same Fan-C version (Fan-C version: 0.8.35) throughout my analysis.
somehow I'm not able to download Fan-C example data, reporting error:

HTTP request sent, awaiting response... 404 Not Found
2020-07-08 15:54:45 ERROR 404: Not Found.

thanks

**Comment by kaukrise** [comment] 2020-07-08 14:06
I'll look into that, but for now can you try using the other method (git clone)?

**Comment by Drosophilid** [comment] 2020-07-08 14:21
sure I'll do that. thanks

**Comment by kaukrise** [comment] 2020-07-08 14:36
I think Keeper may be imposing size restrictions on the gzipped download these days. If you have trouble with git clone (sometimes only the headers of large files are cloned), you can still try to download the example files manually (not all files are required, check the example `auto` command for the ones you need). The link to the Keeper archive is https://keeper.mpdl.mpg.de/d/147906745b634c779ed3/?p=%2Fexamples&mode=list

**Comment by Drosophilid** [comment] 2020-07-09 09:24
Hi KauKrise, I downloaded the example data but compartment matrix directories are empty.

These are the commands that I have used to process my data in Fan-C:
1. I did mapping by using bwa separately.
2. produced restriction enzyme sites file: [**fanc fragments genome.fa MboI fanc.digested.bed]**
3. **[fanc pairs -g fanc.digested.bed -r MboI -t 16 -tmp  -p 2 -s ./fanc.stats --bwa -q 3 -u -m R1.bwa.bam R2.bwa.bam fanc.pairs]**
4. **[fanc hic -b 10k --marginals-plot 10k_marginals-plot-i -t 16 -l -s ./ --statistics-plot 10k_statistics-plot-i -tmp -i -f fanc.pairs hic/10kb.fanc-i.hic]** (also tried with -k normalization).
5. **[fanc compartments -g genome.fa -e 10kb.chrX.pdf -v 10kb.chrX.txt hic/10kb.fanc-i.hic hic/10kb.fanc-i.ab -tmp]**

I also tried to do mapping with Fan-C, unfortunately nothing worked in my case: **[fanc auto 1.fq.gz 2.fq.gz bwa.FANC -g genome.fa -i bwa_index/genome.fa --ice -b 10000 100000 -t 4 -r MboI -q 10]**

any kind of help will be appreciated :)

Thanks

**Comment by kaukrise** [comment] 2020-07-10 07:34
Hi, unfortunately I won't be able to debug those in detail without regular access to my computer, but I will revisit this as soon as I am back in the office.

In the meantime, could you please send me the logs of the commands you posted above? That will help in figuring out what may have gone wrong.

Also, the compartments folder in the example data is supposed to be empty at first. You will need to run the example commands in the links I have sent from the docs to generate the files and plots! Thanks!

**Comment by Drosophilid** [comment] 2020-07-11 14:00
Hi KauKrise, I have processed example data and call compartment which looks fine.

![50kb chr18 hic](https://user-images.githubusercontent.com/64106867/87225763-89ed6e80-c38f-11ea-96da-e99c12e4d663.png)
[1mb.chr18.pdf](https://github.com/vaquerizaslab/fanc/files/4906868/1mb.chr18.pdf)
![1mb chr18 hic ab](https://user-images.githubusercontent.com/64106867/87225770-91147c80-c38f-11ea-8e4d-ab3944f5c19f.png)
![1mb chr18 hic ab oe](https://user-images.githubusercontent.com/64106867/87225772-92de4000-c38f-11ea-969a-c511734dbec5.png)

Thanks

**Comment by kaukrise** [comment] 2020-07-11 14:52
Great, thanks, this suggests that the issue lies somewhere in your data, or how FAN-C handles your data. Have you tried calling compartments in your data at a lower resolution, for example 100kb or 250kb?

**Comment by Drosophilid** [comment] 2020-07-11 15:29
I think problem is with (--ice) correction method in FAN-C, because the above example data I processed without --ice normalisation method. But, when I create hic matrix for the same example data (chr18) with --ice normalisation, compartment segregation again looks weird. 
![1mb chr18](https://user-images.githubusercontent.com/64106867/87227547-14d46600-c39c-11ea-9b02-348fefdc0ac3.png)

**Comment by kaukrise** [comment] 2020-07-11 17:17
Thanks for following this up. To verify that this is the problem, can you tell me exactly what commands you used to arrive at that last plot, including the one with the ICE normalisation? And if you have time, plot the corresponding Hi-C, AB, and O/E matrices (of the Hi-C) again, as you did before?

Did you run the entire example pipeline from scratch, but with the `--ice` option enabled? (If not, could you do so?)

If the ICE norm is at fault, the matrices generated this way would look very different from the ones using KR balancing, I would think.

**Comment by Drosophilid** [comment] 2020-07-11 20:56
Yes, I run the entire example start from mapping using bwa with and without using --ice option to compare the results. 
command I used:

1- fanc auto SRR4271982_chr18_19_1.fastq.gzip SRR4271982_chr18_19_2.fastq.gzip ./fanc.output -g hg19_chr18_19_re_fragments.bed -i bwa-index/hg19_chr18_19.fa -b 100kb 1mb -t 16 -q 3 -tmp 
(is KR balancing is default, because here I don't use any balancing method?)

2- fanc auto SRR4271982_chr18_19_1.fastq.gzip SRR4271982_chr18_19_2.fastq.gzip ./fanc.output -g hg19_chr18_19_re_fragments.bed -i bwa-index/hg19_chr18_19.fa -b 100kb 1mb -t 16 -q 3 -tmp --ice

![1mb chr18 hic](https://user-images.githubusercontent.com/64106867/87233454-da80be00-c3c7-11ea-8cf1-1690373ab427.png)
![1mb chr18 hic ab](https://user-images.githubusercontent.com/64106867/87233458-dc4a8180-c3c7-11ea-84e1-1e28e5451f3a.png)
![1mb chr18 hic ab oe](https://user-images.githubusercontent.com/64106867/87233459-de144500-c3c7-11ea-9694-5a9c1728fae0.png)

Is KR balancing is default, because in first command I don't use any balancing method?
If so, I kind of understand from the comparison of these two different balancing method results (--ice & KR) works very differently.
what you think?

Thanks

**Comment by kaukrise** [comment] 2020-07-11 21:18
This actually looks as though ICE balancing failed for the example data. Could you post the log of the run with `--ice` here to see if there were any error messages? Thanks

**Comment by Drosophilid** [comment] 2020-07-11 22:00
here is log file:
[depth-7308648.err.gz](https://github.com/vaquerizaslab/fanc/files/4907661/depth-7308648.err.gz)

**Comment by kaukrise** [comment] 2020-07-12 07:37
Thank you. There isn't anything in the logs from what I can see - at least ICE started and finished without error. It is possible that for some reason it did not run enough iterations. Would you kindly try this command on the same Hi-C file that you used for the AB calls and send me the log?

```
fanc -vvv hic -i <hic file>
```

Thank you!

**Comment by kaukrise** [comment] 2020-07-12 15:45
I managed to reproduce the issue with the ICE correction myself. At the moment I don't have the proper setup to fix this, but I'll attend to it as soon as I am back in the office. Thank you for bringing this to my attention!

In the meantime, please use the default KR norm, and apologies for any inconvenience!

**Comment by kaukrise** [comment] 2020-07-13 10:40
I pushed a fix for the ICE balancing to GitHub. You can install from the repository, if you want to test it.

It is not yet available via Pypi - I'll update the package when I am back in the office and I know the fix works for you, too.

**Comment by Drosophilid** [comment] 2020-07-13 20:42
Hi Kaukrise, thank you so much to follow up this problem. I sorted it out by using default KR normalization method, and compartment segregation looks normal now. 

![chrX](https://user-images.githubusercontent.com/64106867/87351369-9de4cc00-c559-11ea-8a33-9f8706a63775.png)

But, I would definitely use ICE balancing again just to give it a try.
Thanks

**Comment by Drosophilid** [comment] 2020-07-15 14:09
Hi again, sorry to ask you too many questions. It's really strange that compartment calling worked for one sample but again didn't work for other samples.
normalization method = KR
resolution = 25kb
total A = 2593
total B = 2711
![test](https://user-images.githubusercontent.com/64106867/87555127-55422580-c6b5-11ea-9d1b-9efd61faf1ba.png)

could you please help me to sort out this problem?

Thanks

**Comment by kaukrise** [comment] 2020-07-15 14:52
As before, could you provide me with the exact commands you used, and plots of the Hi-C, the O/E (of the Hi-C) and the AB correlation matrix, all at the same 25kb resolution?

**Comment by Drosophilid** [comment] 2020-07-15 16:02
these are step wise commands how I analyse the data:

1- fanc auto $read1 $read2 ./$out -g genome_digest.bed -i bwa_index/genome.fa -b 25000 50000 100000 -t 16 -tmp -q 3 --iterative
2- fanc compartments -e comp.png hic/binned/25kb.hic hic/binned/25kb.ab -f -v test.txt -g genome.fa

![hic_25kb](https://user-images.githubusercontent.com/64106867/87567944-2a5fcd80-c6c5-11ea-91b4-395c70c56ebf.png)
![AB_25kb](https://user-images.githubusercontent.com/64106867/87567948-2b90fa80-c6c5-11ea-923d-e0a4f01578c2.png)
![AB_OE_25kb](https://user-images.githubusercontent.com/64106867/87567956-2df35480-c6c5-11ea-9e0b-1c0b2c707848.png)

Thanks

**Comment by Drosophilid** [comment] 2020-07-16 08:54
1- I tried 100kb resolution to call AB comp. but don't get any B compartment (Total A=1328 , B=0).
2- with 50kb resolution I finds (total A=2481 , B=172) image attached.
![AB_50kb](https://user-images.githubusercontent.com/64106867/87650499-0a2a2000-c752-11ea-96e0-df11204b032d.png)
3- In my genome I don't have any small contigs but 5 major chromosomes only.
4- I don't do any post-filtering steps, only uses the command sent you before.
5- Here is Hi-C OE plot.
![hic_OE_25kb](https://user-images.githubusercontent.com/64106867/87650921-af44f880-c752-11ea-86c2-9f6084bdb3f5.png)
5- Hi-c uncorrected (-u) plot.
![hic_uncorrected_25kb](https://user-images.githubusercontent.com/64106867/87650869-9dfbec00-c752-11ea-9799-9aa4de95cb6e.png)

**Comment by kaukrise** [comment] 2020-07-16 09:55
Hi, thank you for the additional info!

The plots look as expected, but the sequencing depth off the diagonal is quite low, as suspected. I don't know if this is the underlying cause, but since you successfully got compartments with the other sample, and you processed it the same way, it seems as though it is something specific to this sample.

Here are some more things you can try:

1. Use the second eigenvector for the AB analysis, maybe the first one captures some other property

2. Compare the statistics plot of this sample and the successful one (output as part of `auto`) to see if there are any differences in biases between the samples

3. You mention three replicates - how does the third one look? Also, do you get the same issue when you merge all three?

**Comment by Drosophilid** [comment] 2020-07-16 10:28
Thanks for the quick response.

**You mention three replicates - how does the third one look? Also, do you get the same issue when you merge all three?**
For this sample we only have one replicate, so merging the samples is not an issue.

We do have different tissues Hi-C data (all have one replicate), from them one of the sample worked (the plot I sent you in the beginning), others are not. I have used the same fanc auto command 
(fanc auto $read1 $read2 ./$out -g genome_digest.bed -i bwa_index/genome.fa -b 25000 50000 100000 -t 16 -tmp -q 3 --iterative) 
to process all the samples. That's why I'm bit confused, why compartment calling worked for one sample and not for other samples.

**Comment by kaukrise** [comment] 2020-07-16 10:58
Yeah, my best guess is the sequencing depth since the actual processing did not change. If you want, you can post the filtering statistics barplots of both samples here (in `plots/stats`, ending in `pairs.stats.pdf`), and I can have a look. The two libraries look qualitatively quite different, maybe we can figure out why that way.

Otherwise I can try and have a more in-depth look at your samples when I am back in the office next week.

**Comment by Drosophilid** [comment] 2020-07-16 12:09
1- image from sample that worked for compartment calling.
<img width="925" alt="Screenshot 2020-07-16 at 14 07 23" src="https://user-images.githubusercontent.com/64106867/87669146-ba595200-c76d-11ea-869e-39f857b2e325.png">

2-3 image for samples that doesn't work for compartment calling
<img width="928" alt="Screenshot 2020-07-16 at 14 05 55" src="https://user-images.githubusercontent.com/64106867/87669191-d4933000-c76d-11ea-8cb3-75c81d275404.png">
<img width="927" alt="Screenshot 2020-07-16 at 14 05 41" src="https://user-images.githubusercontent.com/64106867/87669229-e83e9680-c76d-11ea-83fc-f906a7f63c27.png">

**Comment by kaukrise** [comment] 2020-07-16 12:33
Okay, that actually looks like they have almost identical sequencing depth, which is somewhat surprising given the images you posted earlier. Since the level of filtering also looks very similar, I don't think I can debug this further without access to the original files. Maybe we can chat again next week to coordinate.

The only other possibility I can think of is that you may have calculated the AB files before the change to KR norm and it reused the old computation to draw the plots, but you probably thought of that already.

**Comment by Drosophilid** [comment] 2020-07-16 12:43
sure I'll wait, please let me know once you are back in office. I can share my matrix files to you to get better idea.

Thanks

**Comment by kaukrise** [comment] 2020-07-20 11:14
Hi again,

I now had a chance to review the compartment calling code and ran it once more with the test data, also at multiple resolutions. All worked as expected, but one thing I have noticed is that the correlation get increasingly positive with higher resolution. This may be related to the exponential decay of Hi-C matrices.

In any case, I'd be happy to have a look at your matrices, if you are willing to share them. If you prefer not to share the data here, give me an email address and I will contact you so we can arrange something.

**Comment by liz-is** [comment] 2020-07-20 14:53
Hi @Drosophilid, I work in the Vaquerizas lab and have been using fanc for analysing Drosophila data for a while so thought I'd chime in.

In my experience, calling compartments for fly data can be tricky as often the first eigenvector reflects chromosomal position and not compartmentalisation, and this varies between chromosomes and often between samples as well. 

What I always do now is to calculate the first and second eigenvectors of the matrix and inspect them manually (e.g. in a genome browser or by plotting them in R or python). It'll be clear if one of the eigenvectors is actually reflecting the chromosomal position (e.g. for 2R and 3L the first eigenvector often just reflects the centromeric heterochromatin vs the rest of the chromosome arm). If neither of the first two eigenvectors looks like it reflects compartments, I try a larger bin size - in my experience even if I have enough sequencing depth to analyse the matrices at 5kb resolution, I can only get eigenvectors that look sensible at 25kb or 50kb resolution. 

If I'm able to identify which of the first two eigenvectors looks like it represents compartments from manual inspection, then I create a composite bed file that contains the correct eigenvector for each chromosome (e.g. first for X, first for 2L, second for 2R, etc). You can then use this as a reference when plotting the aggregate plot:

` fanc compartments -tmp -e output.png -v composite_eigenvector.bed -g genome.fa hic/binned/25kb.hic hic/binned/25kb.ab`

You can either manually pick the reference eigenvector for each sample, or if you have a control and several treated samples, you could use the control reference eigenvector for all the plots. This can be particularly useful if you have higher sequencing depth in your control for any reason.

**Comment by Drosophilid** [comment] 2020-07-27 13:08
Hi @liz-is thanks for your detailed explanation and sorry for replying you very late, as I was away for holidays.
Yes, I also noticed that PCA eigenvalues varies for different chromosomes (e.g. for some chromosomes PC1 reflect the compartments and for others PC2 explains well). This I check with HicExplorer and CoolTools as well.  But, here in FANC, I was wondering how we can switch eigenvector while plotting the saddle plot (e.g. either to plot PC1 or  PC2)? 

- ### **If I'm able to identify which of the first two eigenvectors looks like it represents compartments from manual inspection, then I create a composite bed file that contains the correct eigenvector for each chromosome (e.g. first for X, first for 2L, second for 2R, etc). You can then use this as a reference when plotting the aggregate plot:**

Yes while using IGV, we can easily identify the correct eigenvectors between PC1 and PC2 for each chromosome. But, then how we can use this corrected eigenvectors bed file to plot a saddle plot in FANC?

* -v composite_eigenvector.bed ......  This value we can only generate but can not assign to the software while plotting the saddle plot right?

**Comment by Drosophilid** [comment] 2020-07-27 13:11
> Hi again,
> 
> I now had a chance to review the compartment calling code and ran it once more with the test data, also at multiple resolutions. All worked as expected, but one thing I have noticed is that the correlation get increasingly positive with higher resolution. This may be related to the exponential decay of Hi-C matrices.
> 
> In any case, I'd be happy to have a look at your matrices, if you are willing to share them. If you prefer not to share the data here, give me an email address and I will contact you so we can arrange something.

Hi @kaukrise you can contact me through the email address mentioned below. Thanks
drosophilid123@gmail.com

**Comment by liz-is** [comment] 2020-07-27 13:32
> * -v composite_eigenvector.bed ......  This value we can only generate but can not assign to the software while plotting the saddle plot right?

You can in fact use a pre-calculated eigenvector bed file to plot the saddle plot! Maybe this isn't clear in the documentation at the moment. You'll get a warning something like this when you reference a bed file that already contains data:
```2020-03-19 09:37:42,371 WARNING Found existing eigenvector at my_eigenvector.bed. Will use the values in the file for enrichment profile calculations. This may not be what you want!```
If you want to use a pre-calculated reference bed file, don't use the `--force` option, as this will instead overwrite the existing data. 

> I was wondering how we can switch eigenvector while plotting the saddle plot (e.g. either to plot PC1 or PC2)?

You can use the `--eigenvector-index` option to `fanc compartments` to choose to use first or second eigenvector (or even third or higher). But this will be applied to the whole genome. As far as I know it's not currently possible to choose different eigenvectors for different chromosomes -- and I think that since this requires manual curation anyway, the simpler solution is to construct the reference eigenvector you want to use as a bed file.

**Comment by Drosophilid** [comment] 2020-07-27 14:44
Thanks @liz-is that will be great help, I would definitely try to plot this way. I actually didn't know that we can use precalculated eigenvector to plot a saddle plot.
I also finds that, remove the centromeric regions before compartment calling also helps to get better visualization. 

Thanks

**Comment by liz-is** [comment] 2020-07-28 14:09
My turn to ask a question, if that's okay! What approach do you use to remove the centromeric regions? That's not something I've tried but it definitely seems like it would be useful here. Is this something you've used with FAN-C or only with other tools?

**Comment by Drosophilid** [comment] 2020-07-30 07:18
First I visualize the whole chromosome in comparison with inactive histone marks that binds on centromeric or we can sat heterochromatic regions (e.g. H3K9me2-3) to identify the centromeric regions. Then I simply create a matrix for the regions without including centromeric part and then call compartments for each chromosome separately.

**Comment by liz-is** [comment] 2020-07-30 14:17
Okay, I see, so you create a matrix that masks the centromeric regions - that makes sense. Thank you! And good luck with your compartment calls! I'd be happy to discuss further if you have any other trouble.

**Closed** 2021-03-23 10:45 UTC
